kind: HTTPEndpoint
apiVersion: api.webmethods.io/v1
metadata:
  name: swagger-endpoint
  version: '1.0'
  namespace: single
spec:
  url: https://petstore3.swagger.io/api/v3
  method: GET
  connectTimeout: 300
  readTimeout: 200
  sslConfig:
    keyStoreAlias: ""
    keyAlias: ""
    truststoreAlias: ""
  serviceRegistryParameters:
    - name: ""
      value: ""
